### ISSUE TITLE
language.md contains both CRLF and LF endings

### ISSUE THREAD

**Issue by schellingerhout** [udacity/create-your-own-adventure#3482]
It seem like the language.md file contains both CRLF (windows style) and LF (Linux style) endings. This causes merge issues. It seems like above the horizontal rule is CRLF and below the horizontal rule is LF

**Comment by meetjoshi** [comment]
@schellingerhout Yes, you are correct. you can simply run:

git diff -U0 -w --no-color | git apply --cached --ignore-whitespace --unidiff-zero -

You will notice that after a git addnw your/file there will still be unstaged changes, it's the whitespaces left. Commit the staged changes.
