### ISSUE TITLE
Time for @casey-collab to do a merge?

### ISSUE THREAD

**Issue by amumtaz** [udacity/create-your-own-adventure#5969]
How long does it take for @casey-collab to do a merge? Mine was submitted a while ago but do not see any merge so far.

**Comment by eosrei** [comment]
For my reference, your PR https://github.com/udacity/create-your-own-adventure/pull/5968 

I suggest asking again in a new comment on that PR.

**Comment by laf-learn** [comment]
It appears that @casey-collab hasn't made any merges since 17 Jan 2017.

**Comment by tgb417** [comment]
I see to be having the same issue.

**Comment by casey-collab** [comment]
https://github.com/udacity/create-your-own-adventure/issues/8918#issuecomment-488843087
