### ISSUE TITLE
@casey-collab Is not merging

### ISSUE THREAD

**Issue by Patrawr** [udacity/create-your-own-adventure#8078]
Looking in other issues it seems the bot has stopped working. Can someone from udacity do a manual merge on PR#8077?

**Comment by ndhananj** [comment]
How long would you have to wait for the merge to happen?

**Comment by kackton** [comment]
Now there are 3.305 pull requests. Is bot became faulty?

**Comment by E-PL** [comment]
Looks like the bot is not active or is faulty. 
Not a big deal but it would be nice if it could be fixed

**Comment by casey-collab** [comment]
![im-back](https://user-images.githubusercontent.com/9259948/57109966-c59c9b00-6ceb-11e9-8df2-e75406641c62.jpg)
