### ISSUE TITLE
Is casey-collab not working?

### ISSUE THREAD

**Issue by gamer-dev** [udacity/create-your-own-adventure#8918]
It has been nearly a month since the last commit. What happened? And also, my own commit is not getting  auto-merged?

**Comment by levyadams** [comment]
Didn't work for me, either.

**Comment by sebasrivera96** [comment]
Yes, I think @casey-collab is not working.

**Comment by hackrmann** [comment]
Yeah same here. Created another branch, modified the story, created the commit on the experimental branch and pushed it here and asked for a pull request. Nothing's happened despite "No merge conflicts". I did do everything right, didn't I? Or is everyone sure by now that @casey-collab  isn't working?

**Comment by ahmedkrmn** [comment]
July 2018 Update : Still not working !

**Comment by ankit217** [comment]
@sebasrivera96 not working

**Comment by sohail-patel** [comment]
September 2018, not working.
Wait... Casey is a he??

**Comment by isabelgh** [comment]
Have the same issue, also September 2018.

**Comment by gabriel197** [comment]
October 2018, same, but if you look at Closed Pull-Requests, they are some how up to date, that means that those got merged?

**Comment by HamzaHajeir** [comment]
R.I.P bot .

**Comment by Hen0k** [comment]
2019 R.I.P Casey

**Comment by diegodebrito** [comment]
Still not working... R.I.P. She was a good bot.

**Comment by casey-collab** [comment]
![im-back-with-the-memes](https://user-images.githubusercontent.com/9259948/57108746-81f46200-6ce8-11e9-9f21-a95ee3bdbf78.jpg)

**Comment by 13rac1** [comment]
Casey Collab was broken and the code thought lost. I've found it and brought it back.
